[supervisord]
nodaemon=true
user=root


[program:websocket]
priority=1
#command=python3 print("ok")
command=python3 -u /scripts/client.py
directory = /etc
log_stdout=true             
log_stderr=true
autostart=true
autorestart=true
stderr_logfile=/var/log/sharr_supervisor.err.log
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0



